---

- name: Insert fake ESGF host entries
  blockinfile:
    path: /etc/hosts
    block: |
      # ESGF Testing
      {% for host, fake_address in fake_hosts.items() %}
      {{ host }} {{ fake_address }}
      {% endfor %}
