
- name: Ensure Config repo is absent
  file:
    path: /tmp/esgf-config
    state: absent

- name: Clone ESGF config repository
  git:
    repo: "{{ esg.config.repo }}"
    version: "{{ esg.config.version }}"
    dest: /tmp/esgf-config
    force: yes

- name: Copy ESGF config files into place
  copy:
    remote_src: yes
    src: /tmp/esgf-config/esgf-prod/{{ item }}.xml
    dest: "{{ esg.config.dir }}/{{ item }}.xml"
    mode: "u=rw,g=r,o=r"
  loop:
    - esgf_ats_static
    - esgf_cogs
    - esgf_endpoints
    - esgf_idp_static
    - esgf_known_providers
    - esgf_search_aliases
    - esgf_shards_static
    - las_servers_static

- name: Write password files
  #no_log: true
  copy:
    content: "{{ admin_pass }}"
    dest: "{{ esg.config.dir }}/{{ item }}"
    mode: 0640
    owner: root
    group: tomcat
  loop:
    - ".esgf_pass"
    - ".esg_keystore_pass"

- name: Write postgres password files
  #no_log: true
  copy:
    content: "{{ all_db.users.super.pass }}"
    dest: "{{ esg.config.dir }}/{{ item }}"
    mode: 0640
    owner: root
    group: tomcat
  loop:
    - ".esg_pg_pass"
    - ".esg_pg_publisher_pass"

# Essential config files for IDP services
- name: Install esgf_idp.xml
  template:
    src: esgf_idp.xml.j2
    dest: "{{ esg.config.dir }}/esgf_idp.xml"

- name: Install esgf_ats.xml
  template:
    src: esgf_ats.xml.j2
    dest: "{{ esg.config.dir }}/esgf_ats.xml"

- name: Install esgf_azs.xml
  template:
    src: esgf_azs.xml.j2
    dest: "{{ esg.config.dir }}/esgf_azs.xml"
