
# Entry point for installing base components

- name: Install epel-release
  package:
    name: epel-release

- name: Install basic utilities
  package:
    name:
      - unzip
      - lsof
      - bind-utils
      - git
      - wget
      - gcc
      - openssl
      - openssl-devel
      - nss
      - curl
      - libcurl
      - "{{ pkgs.psycopg2 }}"
      - postgresql-devel
    state: latest

- name: Import postgres tasks
  import_tasks: postgres.yml
  when: need_local_postgres|default(true)

- name: Import base tasks
  include_tasks: "{{ base_task }}.yml"
  loop:
    - properties
    - config
  loop_control:
    loop_var: base_task

- name: Include Globus Tools
  when: globus_user is defined and globus_pass is defined
  include_role:
    name: globus_tools
