
# Install the postgres server and devel files

## this now handled by "Install basic utilities" (hence not dependent on
## use_local_postgres) because it is needed in schema_migrate even where
## local postgres server is not required

#- name: Ensure psycopg2 is installed and pg_config is available
#  package:
#    name:
#      - "{{ pkgs.psycopg2 }}"
#      - postgresql-devel

- name: Install tier 1 repo
  yum:
    name: pgdg-tier1-repo
    state: latest

- name: Ensure postgres is installed
  package:
    name:
      - "{{ pkgs.postgres_devel }}"
      - "{{ pkgs.postgres_server }}"

- name: Initialise PostgreSQL on CentOS/RHEL 7
  command: /usr/pgsql-9.6/bin/postgresql96-setup initdb
  register: postgres_initdb
  failed_when: "postgres_initdb.rc != 0 and 'Data directory is not empty!' not in postgres_initdb.stdout"
  changed_when: postgres_initdb.rc == 0

- name: Install pg_hba.conf file
  copy:
    src: postgres/pg_hba.conf
    dest: /var/lib/pgsql/9.6/data/pg_hba.conf

- name: Start postgres
  service:
    name: postgresql-9.6
    state: started
    enabled: yes

- name: Create db super user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ all_db.users.super.name }}"
    password: "{{ all_db.users.super.pass }}"
    role_attr_flags: SUPERUSER

- name: Create ESGCET database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ all_db.db }}"
